# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BsvUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=b'ca', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_submitted', models.CharField(max_length=10, null=True)),
                ('hour_submitted', models.CharField(max_length=5, null=True)),
                ('places_lived', models.CharField(max_length=500)),
                ('worked_at', models.CharField(max_length=500)),
                ('music_at_work', models.CharField(max_length=200)),
                ('play_instrument', models.BooleanField(default=True)),
                ('instrument', models.CharField(max_length=200, null=True)),
                ('like_singing', models.CharField(max_length=200)),
                ('group_singing', models.CharField(max_length=500)),
                ('like_dancing', models.CharField(max_length=200)),
                ('like_dancing_bool', models.BooleanField(default=False)),
                ('preferred_genres', models.CharField(max_length=500)),
                ('preferred_songs', models.CharField(max_length=1500)),
                ('preferred_artists', models.CharField(max_length=1500)),
                ('sing_instrumental', models.CharField(max_length=200)),
                ('upbeat_calm', models.CharField(max_length=200)),
                ('cheerful_melancholic', models.CharField(max_length=200)),
                ('listen_instruments', models.CharField(max_length=500)),
                ('listen_language', models.CharField(max_length=500)),
                ('childhood', models.CharField(max_length=100, null=True)),
                ('childhood_songs', models.CharField(max_length=500)),
                ('youth_dance', models.CharField(max_length=100, null=True)),
                ('youth_dance_songs', models.CharField(max_length=500)),
                ('radio', models.CharField(max_length=100, null=True)),
                ('radio_programmes', models.CharField(max_length=800)),
                ('tv', models.CharField(max_length=100, null=True)),
                ('tv_programmes', models.CharField(max_length=800)),
                ('wedding_songs', models.CharField(max_length=500)),
                ('good_memories', models.CharField(max_length=100, null=True)),
                ('good_memories_songs', models.CharField(max_length=500)),
                ('bad_memories', models.CharField(max_length=100, null=True)),
                ('bad_memories_song', models.CharField(max_length=200)),
                ('all_preferred_songs', models.CharField(max_length=3000)),
                ('desired_playlist_length', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('year', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(max_length=500, null=True)),
                ('spotify_id', models.CharField(max_length=200, null=True)),
                ('preview', models.CharField(default=b'#', max_length=200, null=True)),
                ('duration_ms', models.IntegerField(default=0, null=True)),
                ('popularity', models.IntegerField(default=0, null=True)),
                ('acousticness', models.FloatField(default=0, null=True)),
                ('danceability', models.FloatField(default=0, null=True)),
                ('energy', models.FloatField(default=0, null=True)),
                ('instrumentalness', models.FloatField(default=0, null=True)),
                ('mode', models.IntegerField(default=0, null=True)),
                ('tempo', models.IntegerField(default=0, null=True)),
                ('valence', models.FloatField(default=0, null=True)),
                ('user_popularity', models.IntegerField(default=0, null=True)),
                ('is_a_hit', models.BooleanField(default=False)),
                ('is_special_genre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('birth_place', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(default=b'ca', max_length=10, null=True)),
                ('current_view', models.CharField(max_length=200, null=True)),
                ('playlist_length', models.IntegerField(null=True)),
                ('playlist_url', models.CharField(max_length=500, null=True)),
                ('playlist_feedback_text', models.CharField(max_length=1000, null=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recommender.Forms')),
                ('negative_feedback_tracks', models.ManyToManyField(to='Recommender.Track')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(max_length=500, null=True)),
                ('playlist_position', models.IntegerField(null=True)),
                ('playlist_group', models.CharField(max_length=50, null=True)),
                ('feedback_familiar', models.CharField(max_length=10, null=True)),
                ('feedback_like', models.CharField(max_length=10, null=True)),
                ('feedback_memories', models.CharField(max_length=10, null=True)),
                ('feedback_listen_again', models.CharField(max_length=10, null=True)),
                ('feedback_text', models.CharField(max_length=1000, null=True)),
                ('feedback_done', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommender.Track')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='playlist',
            field=models.ManyToManyField(to='Recommender.UserTrack'),
        ),
        migrations.AddField(
            model_name='bsvuser',
            name='profiles',
            field=models.ManyToManyField(to='Recommender.UserProfile'),
        ),
        migrations.AddField(
            model_name='bsvuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
