# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsvuser',
            name='current_profile',
            field=models.IntegerField(null=True),
        ),
    ]
